# Generated by Django 6.0 on 2026-01-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('estoques', '0003_logretirada_destino'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together={('empresa', 'produto')},
        ),
    ]
