# Generated by Django 5.2.8 on 2025-11-20 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('produtos', '0007_remove_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
