# Generated by Django 5.2.8 on 2025-11-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidate',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
