# Generated by Django 5.2.8 on 2025-11-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_quantidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quantidate',
            new_name='quantidade',
        ),
    ]
