# Generated by Django 5.2.8 on 2025-11-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_minima',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
