# Generated by Django 5.2.8 on 2025-11-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_quantidade_minima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade_minima',
        ),
    ]
