# Generated by Django 5.2.8 on 2025-11-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_remove_produto_quantidade_minima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
    ]
