# Generated by Django 6.0 on 2025-12-27 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em análise'), ('EM_PROCESSO_AUTORIZACAO', 'Em processo de autorização'), ('AUTORIZADA', 'Autorizada'), ('UNIDA', 'Unida'), ('CONSOLIDADA', 'Consolidada'), ('EM_PROCESSO', 'Em Processo de Compra'), ('EM_ENTREGA', 'Em Rota de Entrega'), ('RECEBIDA', 'Itens Recebidos')], default='EM_ANALISE', max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_compra', to='empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ItemListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_desejada', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.listacompra')),
            ],
        ),
        migrations.CreateModel(
            name='LogAlteracaoLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_antiga', models.PositiveIntegerField()),
                ('quantidade_nova', models.PositiveIntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes', to='compras.listacompra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
