# Generated by Django 5.2.8 on 2025-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacompra',
            name='recebido',
            field=models.BooleanField(default=False),
        ),
    ]
