# Generated by Django 6.0 on 2025-12-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacompra',
            name='listas_unidas',
            field=models.ManyToManyField(blank=True, related_name='lista_principal', to='compras.listacompra'),
        ),
        migrations.AlterField(
            model_name='listacompra',
            name='status',
            field=models.CharField(choices=[('EM_CRIACAO', 'Em Criação'), ('EM_PROCESSO_AUTORIZACAO', 'Em processo de autorização'), ('AUTORIZADA', 'Autorizada'), ('UNIDA', 'Unida'), ('EM_PROCESSO_CONSOLIDACAO', 'Em processo de consolidação'), ('CONSOLIDADA', 'Consolidada'), ('EM_PROCESSO_COMPRA', 'Em Processo de Compra'), ('EM_ENTREGA', 'Em Rota de Entrega'), ('RECEBIDA', 'Itens Recebidos')], default='EM_CRIACAO', max_length=30),
        ),
    ]
