# Generated by Django 6.0 on 2026-01-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_listacompra_listas_unidas_alter_listacompra_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlistacompra',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
