# Generated by Django 6.0 on 2026-01-12 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_itemlistacompra_preco_unitario'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacompra',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retiradas_destino', to='empresas.empresa'),
        ),
    ]
