# Generated by Django 6.0 on 2026-01-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_listacompra_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listacompra',
            name='destino',
        ),
    ]
